# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('upwd', models.CharField(max_length=40)),
                ('uemil', models.CharField(max_length=30)),
                ('urelname', models.CharField(default='', max_length=20)),
                ('uadr', models.CharField(default='', max_length=100)),
                ('uphone', models.CharField(default='', max_length=11)),
            ],
        ),
    ]
